format = """
$directory\
$git_branch\
$git_status\
$fill\
$python$cmd_duration$status $time\
$line_break\
$character"""

right_format = """
$username\
$hostname\
"""

[username]
style_user = 'dimmed white'
style_root = 'red bold'
format = '[$user]($style)'
show_always = true
# disabled = true

[hostname]
ssh_only = false
format = '[@$hostname](dimmed white)'
# disabled = true

[directory]
style = "bold blue"
truncation_length = 2
fish_style_pwd_dir_length = 1

[character]
# success_symbol = '[](bold green)'
# success_symbol = '[󰅂](bold green)'
error_symbol = '[](bold red)'

[fill]
symbol = ' '

[git_branch]
format = "[$branch]($style)"
style = "dimmed white"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218)($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[status]
format = "[$status]($style)"
style = "bold red"
disabled = false
pipestatus = true
pipestatus_format = "[$pipestatus]($style) "
pipestatus_separator = "|"
map_symbol = false

[python]
format = "[$virtualenv]($style) "
style = "bright-black"

[time]
disabled = false
style = "bold white"
format = '[$time]($style) '
time_format = '%H:%M'
