format = """$username\
[](bg:peach fg:crust)\
$directory\
[](fg:peach bg:green)\
$git_branch\
$git_status\
[](fg:green bg:sapphire)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:sapphire bg:mauve)\
$docker_context\
$conda\
[](fg:mauve bg:surface0)\
$time\
$cmd_duration\
[ ](fg:surface0)\
$line_break$character"""

palette = "catppuccin_mocha"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[username]
show_always = true
style_user = "bold bg:crust fg:subtext1"
style_root = "bold bg:crust fg:red"
format = '[  $user ]($style)'

[directory]
style = "bold fg:mantle bg:peach"
read_only = ' '
format = "[ $read_only $path ]($style)"
truncation_length = 2
fish_style_pwd_dir_length = 1

[git_branch]
style = "bg:green"
format = '[[ $symbol$branch ](fg:base bg:green)]($style)'

[git_status]
style = "bg:green"
format = '[[($all_status$ahead_behind )](fg:base bg:green)]($style)'

[nodejs]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:mantle bg:sapphire)]($style)'

[c]
symbol = " "
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:mantle bg:sapphire)]($style)'

[rust]
symbol = " "
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:mantle bg:sapphire)]($style)'

[golang]
symbol = " "
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:mantle bg:sapphire)]($style)'

[php]
symbol = " "
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:mantle bg:sapphire)]($style)'

[java]
symbol = " "
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:mantle bg:sapphire)]($style)'

[kotlin]
symbol = " "
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:mantle bg:sapphire)]($style)'

[haskell]
symbol = " "
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:mantle bg:sapphire)]($style)'

[python]
symbol = " "
style = "bg:sapphire"
format = '[[ $symbol( $version $virtualenv) ](fg:mantle bg:sapphire)]($style)'

[docker_context]
symbol = " "
style = "bg:sapphire"
format = '[[ $symbol( $context) ](fg:mantle bg:mauve)]($style)'

[conda]
style = "bg:sapphire"
format = '[[ $symbol( $environment) ](fg:mantle bg:mauve)]($style)'

[time]
disabled = true
time_format = "%R"  # Hour:Minute Format
style = "bg:surface0"
format = '[[  $time ](fg:subtext0 bg:surface0)]($style)'

[cmd_duration]
disabled = false
style = " bg:surface0"
show_milliseconds = true
format = '[[ took $duration ](bold italic fg:subtext0 bg:surface0)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[ ](bold fg:green)'
error_symbol = '[✘](bold fg:red)'
vimcmd_symbol = '[❮](bold fg:teal)'
vimcmd_replace_one_symbol = '[❮](bold fg:lavender)'
vimcmd_replace_symbol = '[❮](bold fg:lavender)'
vimcmd_visual_symbol = '[❮](bold fg:lavender)'
